# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class TestNavigationCheck():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()



    def test_navigationCheck(self):
        self.driver.get("https://magento.softwaretestingboard.com/")
        # self.driver.set_window_size(1534, 912)
        self.driver.maximize_window()

        wait = WebDriverWait(self.driver, 10)  # waits up to 10 seconds

        # Hover over "Women"
        element = wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "#ui-id-4 > span:nth-child(2)")))
        ActionChains(self.driver).move_to_element(element).perform()

        # Hover over "Tops"
        element = wait.until(EC.visibility_of_element_located((By.ID, "ui-id-9")))
        ActionChains(self.driver).move_to_element(element).perform()

        # Click on "Hoodies and Sweatshirts"
        wait.until(EC.element_to_be_clickable((By.ID, "ui-id-12"))).click()

        # Open first filter 'Style'
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".filter-options-item:nth-child(1)"))).click()
        wait.until(EC.element_to_be_clickable(
            (By.CSS_SELECTOR, ".filter-options-item:nth-child(1) > .filter-options-title"))).click()
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".allow .item:nth-child(3) > a"))).click()

        # Select next filters with waits: 'Size'
        wait.until(EC.element_to_be_clickable((By.XPATH, "//div[2]/div[3]/div"))).click()
        wait.until(EC.element_to_be_clickable((By.XPATH, "//div[2]/div[3]/div/div"))).click()
        # wait.until(
        #     EC.element_to_be_clickable((By.XPATH, "//div[@id='narrow-by-list']/div/div[2]/div/div/a[3]/div"))).click()

        # Select the next Filer: 'Color'
        wait.until(EC.element_to_be_clickable((By.XPATH, "//div[2]/div[3]/div[2]"))).click()
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, "//div[2]/div[3]/div[2]/div"))).click()
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, "//div[2]/div[3]/div[2]/div"))).click()
        wait.until(EC.element_to_be_clickable(
            (By.CSS_SELECTOR, ".swatch-option-link-layered:nth-child(2) > .swatch-option"))).click()

        # Hover over product image
        element = wait.until(EC.visibility_of_element_located(
            (By.XPATH, "//main[@id='maincontent']/div[3]/div/div[3]/ol/li/div")))
        ActionChains(self.driver).move_to_element(element).perform()

        # Click "Add to Cart"
        wait.until(EC.element_to_be_clickable(
            (By.XPATH, "//main[@id='maincontent']/div[3]/div/div[3]/ol/li/div/div/div[3]/div/div/form/button/span"))).click()

        time.sleep(10)

        # # Click cart icon
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".showcart > .counter"))).click()

        time.sleep(5)

        wait.until(EC.element_to_be_clickable((By.XPATH, "//button[@id='top-cart-btn-checkout']"))).click()

        time.sleep(5)

        self.driver.find_element(By.XPATH, "//div[@id=\'opc-sidebar\']/div/div/div").click()

        product_name = self.driver.execute_script("return window.checkoutConfig.quoteItemData[0].name;")

        # Assert the product name
        assert product_name == "Eos V-Neck Hoodie", f"Expected 'Eos V-Neck Hoodie', but got '{product_name}'"

        self.driver.close()

