# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.calculator.net/body-fat-calculator.html")
    self.driver.set_window_size(1436, 855)
    self.driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(2) > .rbmark").click()
    self.driver.find_element(By.NAME, "cage").click()
    self.driver.find_element(By.NAME, "cage").clear()
    self.driver.find_element(By.NAME, "cage").send_keys("35")
    self.driver.find_element(By.NAME, "cweightkgs").click()
    self.driver.find_element(By.NAME, "cweightkgs").clear()
    self.driver.find_element(By.NAME, "cweightkgs").send_keys("200")
    self.driver.find_element(By.ID, "cheightmeter").click()
    self.driver.find_element(By.ID, "cheightmeter").clear()
    self.driver.find_element(By.ID, "cheightmeter").send_keys("180")
    self.driver.find_element(By.ID, "cneckmeter").click()
    self.driver.find_element(By.ID, "cneckmeter").clear()
    self.driver.find_element(By.ID, "cneckmeter").send_keys("34")
    self.driver.find_element(By.ID, "cwaistmeter").click()
    self.driver.find_element(By.ID, "cwaistmeter").clear()
    self.driver.find_element(By.ID, "cwaistmeter").send_keys("100")
    self.driver.find_element(By.ID, "chipmeter").click()
    self.driver.find_element(By.ID, "chipmeter").clear()
    self.driver.find_element(By.ID, "chipmeter").send_keys("85")
    self.driver.find_element(By.NAME, "x").click()

    result_text = self.driver.find_element(By.CSS_SELECTOR, "font > b").text
    assert result_text == "Body Fat: 29.9%", f"Expected 'Body Fat: 29.9%' but got '{result_text}'"

    print("Female Test Case Result:", result_text)
